# Generated by Django 4.2.1 on 2023-07-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_volunteer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='name',
        ),
    ]
