# Generated by Django 4.2.1 on 2023-07-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitie', '0001_initial'),
        ('users', '0006_remove_volunteer_email_remove_volunteer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='activities',
            field=models.ManyToManyField(null=True, to='activitie.activitiedetailpage'),
        ),
    ]
