# Generated by Django 4.2.1 on 2023-07-04 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_volunteer_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='activities',
        ),
    ]
