# Generated by Django 4.2.1 on 2023-07-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_volunteer_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(help_text='user phone number', max_length=20),
        ),
    ]
