# Generated by Django 4.2.1 on 2023-08-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_volunteer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='neighborhood',
            field=models.CharField(default='barrio falso', help_text="volunteer's neighborhood", max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='university',
            field=models.CharField(default='UCC', help_text="volunteer's university", max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='university_file',
            field=models.CharField(default='legajo falso', help_text="volunteer's university file", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='address',
            field=models.CharField(help_text="volunteer's home address", max_length=80),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(help_text="volunteer's phone number", max_length=20),
        ),
    ]
