# Generated by Django 4.2.1 on 2023-10-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_volunteer_birthdate_volunteer_career_volunteer_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='validated',
            field=models.BooleanField(default=True, help_text='Voluntario validado'),
            preserve_default=False,
        ),
    ]
