# Generated by Django 4.2.1 on 2023-12-26 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_volunteer_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='ingreso',
            field=models.DateField(default=datetime.date(2023, 12, 26), help_text='Fecha de ingreso al VUCC'),
        ),
    ]
