# Generated by Django 4.2.1 on 2023-12-26 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_volunteer_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='ingreso',
            field=models.DateField(default=datetime.date.today, help_text='Fecha de ingreso al VUCC'),
        ),
    ]
