# Generated by Django 4.2.1 on 2023-12-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_volunteer_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='coordinador',
            field=models.BooleanField(default=False, help_text='Coordinador de voluntariado'),
        ),
    ]
