# Generated by Django 4.2.1 on 2024-02-04 22:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0016_volunteer_coordinador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='address',
            field=models.CharField(max_length=80, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='birthdate',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='career',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='coordinador',
            field=models.BooleanField(default=False, verbose_name='Coordinador del VUCC'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='dni',
            field=models.CharField(max_length=20, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='ingreso',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de ingreso al VUCC'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='neighborhood',
            field=models.CharField(max_length=80, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='university',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Universidad'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='university_file',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Legajo universitario'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario vinculado'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='validated',
            field=models.BooleanField(default=False, help_text='Voluntario validado', verbose_name='Validado'),
        ),
    ]
