# Generated by Django 4.2.1 on 2024-02-07 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_volunteer_address_alter_volunteer_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'Voluntario', 'verbose_name_plural': 'Voluntarios'},
        ),
    ]
