# Generated by Django 4.2.1 on 2024-02-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_volunteer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='career',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='university_file',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Legajo universitario'),
        ),
    ]
