# Generated by Django 4.2.1 on 2023-11-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='activity_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
