# Generated by Django 4.2.1 on 2024-02-07 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_volunteer_options'),
        ('activitie', '0012_alter_activitiedetailpage_content'),
        ('attendances', '0002_attendance_activity_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record', to='activitie.activitiedetailpage', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='activity_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título de la actividad'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.volunteer', verbose_name='Voluntario'),
        ),
    ]
