# Generated by Django 4.2.1 on 2023-08-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0012_volunteer_birthdate_volunteer_career_volunteer_dni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField()),
                ('volunteers', models.ManyToManyField(related_name='volunteering', to='users.volunteer')),
            ],
        ),
    ]
