# Generated by Django 4.2.1 on 2024-01-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_volunteer_coordinador'),
        ('volunteerings', '0002_volunteering_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteering',
            name='coordinadores',
            field=models.ManyToManyField(related_name='coordina', to='users.volunteer'),
        ),
    ]
