# Generated by Django 4.2.1 on 2024-02-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_volunteer_coordinador'),
        ('volunteerings', '0003_volunteering_coordinadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteering',
            name='coordinadores',
            field=models.ManyToManyField(blank=True, related_name='coordina', to='users.volunteer'),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='volunteering', to='users.volunteer'),
        ),
    ]
