# Generated by Django 4.2.1 on 2024-02-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerings', '0005_alter_volunteering_coordinadores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteering',
            name='short_description',
            field=models.CharField(blank=True, null=True, verbose_name='Breve descripción, para vista en celulares'),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='description',
            field=models.CharField(verbose_name='Descripción del voluntariado'),
        ),
    ]
