# Generated by Django 4.2.1 on 2024-02-07 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerings', '0006_volunteering_short_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteering',
            options={'verbose_name': 'Voluntario', 'verbose_name_plural': 'Voluntarios'},
        ),
    ]
