# Generated by Django 4.2.1 on 2024-02-07 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerings', '0007_alter_volunteering_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteering',
            options={'verbose_name': 'Voluntariado', 'verbose_name_plural': 'Voluntariados'},
        ),
    ]
