# Generated by Django 4.2.1 on 2024-02-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerings', '0008_alter_volunteering_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteering',
            name='Instagram',
            field=models.CharField(blank=True, help_text='Contacto de Instagram para el voluntariado', null=True),
        ),
        migrations.AddField(
            model_name='volunteering',
            name='Whatsapp',
            field=models.CharField(blank=True, help_text='Contacto de Whatsapp para el voluntariado', null=True),
        ),
    ]
