# Generated by Django 4.2.1 on 2023-07-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_volunteer_activities'),
        ('activitie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiedetailpage',
            name='volunteers',
            field=models.ManyToManyField(to='users.volunteer'),
        ),
    ]
