# Generated by Django 4.2.1 on 2023-08-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitie', '0004_activitielistingpage_related_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiedetailpage',
            name='activity_end_date',
            field=models.DateField(blank=True, help_text='fecha inicio de vigencia del post de la actividad', null=True),
        ),
        migrations.AddField(
            model_name='activitiedetailpage',
            name='activity_start_date',
            field=models.DateField(blank=True, help_text='fecha inicio de vigencia del post de la actividad', null=True),
        ),
    ]
