# Generated by Django 4.2.1 on 2023-08-28 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerings', '0001_initial'),
        ('activitie', '0006_activitiedetailpage_volunteering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiedetailpage',
            name='volunteering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='volunteerings.volunteering'),
        ),
    ]
