# Generated by Django 4.2.1 on 2024-02-04 20:12

import datetime
from django.db import migrations, models
import streams.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activitie', '0008_remove_activitielistingpage_related_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitielistingpage',
            name='custom_title',
        ),
        migrations.AlterField(
            model_name='activitiedetailpage',
            name='activity_end_date',
            field=models.DateField(default=datetime.date.today, help_text='Fecha inicio de vigencia del post de la actividad'),
        ),
        migrations.AlterField(
            model_name='activitiedetailpage',
            name='activity_start_date',
            field=models.DateField(default=datetime.date.today, help_text='Fecha inicio de vigencia del post de la actividad'),
        ),
        migrations.AlterField(
            model_name='activitiedetailpage',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add a title', required=True)), ('text', wagtail.blocks.TextBlock(help_text='Add a text', required=True))])), ('full_rich_text', streams.blocks.RichTextBlock()), ('simple_rich_text', streams.blocks.SimpleTextBlock())], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='activitiedetailpage',
            name='custom_title',
            field=models.CharField(help_text='Título de la actividad', max_length=100),
        ),
    ]
