# Generated by Django 4.2.1 on 2024-02-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitie', '0010_alter_activitiedetailpage_activity_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitiedetailpage',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='activitielistingpage',
            options={'verbose_name': 'Página de listado de actividades', 'verbose_name_plural': 'Páginas de listado de actividades'},
        ),
    ]
