# Generated by Django 4.2.1 on 2024-02-04 21:26

from django.db import migrations
import streams.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activitie', '0011_alter_activitiedetailpage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiedetailpage',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Título de la sección', label='Título', required=True)), ('text', wagtail.blocks.TextBlock(help_text='Texto de la sección', label='Texto', required=True))])), ('full_rich_text', streams.blocks.RichTextBlock()), ('simple_rich_text', streams.blocks.SimpleTextBlock())], blank=True, null=True, use_json_field=True),
        ),
    ]
