# Generated by Django 4.2.1 on 2023-07-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_options_homepage_banner_cta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'HOME PAGE', 'verbose_name_plural': 'HOME PAGES'},
        ),
    ]
