# Generated by Django 4.2.1 on 2024-02-04 21:26

from django.db import migrations
import streams.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_homepage_content_alter_homepage_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Título de la sección', label='Título', required=True)), ('text', wagtail.blocks.TextBlock(help_text='Texto de la sección', label='Texto', required=True))])), ('full_rich_text', streams.blocks.RichTextBlock()), ('simple_rich_text', streams.blocks.SimpleTextBlock()), ('horizontal_allign_elements', wagtail.blocks.StructBlock([('elements', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('element', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Imagen', required=True)), ('text', wagtail.blocks.RichTextBlock(help_text='Contenido', label='Texto', required=True)), ('link', wagtail.blocks.URLBlock(help_text='URL de la página a redireccionar en caso de desearlo, de no ser así ignorar este campo', label='Link', required=False))]))]), label='Elementos'))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
