# Generated by Django 4.2.1 on 2024-02-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0062_alter_flexpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='flexpage',
            name='titulo',
            field=models.CharField(blank=True, help_text='Título de la página', max_length=100, null=True),
        ),
    ]
