# Generated by Django 4.2.1 on 2024-02-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0064_alter_flexpage_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Página flexible', 'verbose_name_plural': 'Páginas flexibles'},
        ),
    ]
