# Generated by Django 4.2.1 on 2024-02-08 23:04

from django.db import migrations
import streams.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0066_alter_flexpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Título de la sección', label='Título', required=True)), ('text', wagtail.blocks.TextBlock(help_text='Texto de la sección', label='Texto', required=True))])), ('full_rich_text', streams.blocks.RichTextBlock()), ('simple_rich_text', streams.blocks.SimpleTextBlock()), ('horizontal_allign_elements', wagtail.blocks.StructBlock([('elements', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('element', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Imagen', required=True)), ('text', wagtail.blocks.RichTextBlock(help_text='Contenido', label='Texto', required=True)), ('link', wagtail.blocks.URLBlock(help_text='URL de la página a redireccionar en caso de desearlo, de no ser así ignorar este campo', label='Link', required=False))]))]), label='Elementos'))])), ('faq', wagtail.blocks.StructBlock([('questions', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(label='Pregunta', required=True)), ('responses', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('response', wagtail.blocks.RichTextBlock(label='Respuesta', required=True))]), label='Respuestas'))]), label='Preguntas'))])), ('donaciones', wagtail.blocks.StructBlock([('elemento_donacion', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('voluntariado', wagtail.blocks.CharBlock(help_text='Título del item de donacion, por ejemplo, nombre del voluntariado', label='Título campaña donación', required=True)), ('imagen', wagtail.images.blocks.ImageChooserBlock(help_text='Imagen de la campaña de donación, por ejemplo, imagen del voluntariado', required=False)), ('alias', wagtail.blocks.CharBlock(help_text='Alias para recibir donaciones', required=False)), ('sugeridos', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(blank='True', help_text='Elementos sugeridos para donar', required=False), blank=True, required=False)), ('contactos', wagtail.blocks.StreamBlock([('Instagram', wagtail.blocks.StructBlock([('cuenta', wagtail.blocks.CharBlock(help_text='Nombre cuenta instagram', required=True))])), ('Whatsapp', wagtail.blocks.StructBlock([('numero', wagtail.blocks.CharBlock(help_text='Número celular', required=True))]))], required=False, use_json_field=True))])))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
