# Generated by Django 4.2.1 on 2023-07-06 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_volunteer_activities'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='proprietary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.volunteer'),
            preserve_default=False,
        ),
    ]
