# Generated by Django 4.2.1 on 2023-07-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_brand_vehicle_model_vehicle_proprietary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(default='nada', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default='nada', max_length=20),
            preserve_default=False,
        ),
    ]
