# Generated by Django 4.2.1 on 2023-07-07 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitie', '0002_activitiedetailpage_volunteers'),
        ('vehicles', '0003_alter_vehicle_brand_alter_vehicle_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='activitie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activitie.activitiedetailpage'),
        ),
    ]
