# Generated by Django 4.2.1 on 2023-07-07 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_volunteer_activities'),
        ('vehicles', '0004_vehicle_activitie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='proprietary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='users.volunteer'),
        ),
    ]
