# Generated by Django 4.2.1 on 2023-08-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_vehicle_proprietary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='room',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
