# Generated by Django 4.2.1 on 2024-01-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitie', '0007_alter_activitiedetailpage_volunteering'),
        ('vehicles', '0006_vehicle_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='activitie',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='activitie',
            field=models.ManyToManyField(to='activitie.activitiedetailpage'),
        ),
    ]
