# Generated by Django 4.2.1 on 2024-01-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_alter_vehicle_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='domain',
            field=models.CharField(max_length=10),
        ),
    ]
