# Generated by Django 4.2.1 on 2023-07-14 18:13

from django.db import migrations
import streams.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinlistingpage',
            name='content',
            field=wagtail.fields.StreamField([('bulletins', streams.blocks.Bulletin())], blank=True, null=True, use_json_field=True),
        ),
    ]
