# Generated by Django 4.2.1 on 2023-07-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_bulletinlistingpage_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BulletinDetailPage',
        ),
    ]
